import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {createStabilityDatabase} from './helpers/stability.mjs';
import {callRpc,TEST_ACCESS_CODE} from './helpers/database.mjs';
import {emptyDocument,imagesIn} from '../web/js/maps/model.js';
import {upgradeDocument,compileDocument,goalDefault} from '../web/js/maps/features.js';
import {publishFixture} from './helpers/games.mjs';

const cell=(id,type,x,y,number=7,extra={})=>({id,type,x,y,w:type==='monster'?8:4,h:type==='monster'?8:4,number,start:false,dimmed:false,...extra});
function fixture(){const d=upgradeDocument(emptyDocument());d.rooms=[cell(1,'normal',0,0,6,{start:true}),cell(2,'normal',4,0,7,{dimmed:true}),cell(3,'monster',8,0,null,{name:'Troll',hits:5,attacks:[{number:8,state:'active'}],rewardFirst:3,rewardLater:1,image:null,imageLayout:null}),cell(4,'portal',0,4,9),cell(5,'portal',40,0,9),cell(6,'crazy',44,0,null,{requirements:[3,8,'doubles']}),cell(7,'trap',48,0,5,{trapKind:'diamonds',trapCost:2}),cell(8,'bonus',52,0,null,{name:'Steinrätsel',hits:2,attacks:[{number:6,state:'active'}],rewardFirst:2,rewardLater:0,image:null,imageLayout:null}),cell(9,'goldSack',56,0),cell(10,'goldCoin',60,0)];d.rules.goals=[{...goalDefault(),type:'allType',fieldType:'trap',reward:{first:5,later:2}},{...goalDefault(),type:'connect',cellIds:[1,10],reward:{first:4,later:0}}];d.allowedPowerups.push('binocular');return d;}
test('Upgrade leaves the original immutable; only legacy specials/minibosses change meaning',()=>{const d=emptyDocument();d.rooms=[cell(1,'special',0,0),cell(2,'miniboss',4,0)];const n=upgradeDocument(d);assert.equal(d.format,'dungeon-layout-v6');assert.deepEqual(n.rooms.map(r=>r.type),['rune','bonus']);assert.equal(n.rules.version,2);});
test('Automatic gray links respect doors, runes reach remote bosses, portals pair and goals follow types',()=>{const d=fixture(),enemy=compileDocument(d).rooms[2];assert.ok(enemy.attacks.some(a=>a.number===7&&a.state==='locked'));const n=compileDocument(d);assert.deepEqual(n.rules.portalPairs,[[4,5]]);assert.deepEqual(n.rules.goals[0].cellIds,[7]);d.closedDoors['2:3']=true;assert.equal(compileDocument(d).rules.unlocks.length,0);d.rooms.push(cell(11,'rune',64,0,10),cell(12,'boss',68,0,null,{w:16,h:8,attacks:[]}));assert.ok(compileDocument(d).rules.unlocks.some(u=>u.sourceCellId===11&&u.targetCellId===12&&u.number===10));});
test('Images include live/defeated art, print images, background and thumbnail',()=>{const d=fixture();d.rooms[2].image={src:'live'};d.rooms[2].defeatedImage={src:'dead'};d.previewImage={src:'preview'};assert.deepEqual(imagesIn(d).map(i=>i.src),['live','dead','preview']);});
test('Editor format on PostgreSQL: canonical save, validation, frozen graph, legacy compatibility',{timeout:120000},async t=>{
 const db=await createStabilityDatabase(),sql=await readFile(new URL('../supabase/migrations/014_editor_upgrade.sql',import.meta.url),'utf8');let user,map,rev;const editor=randomUUID();
 const rpc=(name,args={})=>callRpc(db,name,{p_session_token:user.session.token,...args});
 async function save(d){const r=await rpc('save_map',{p_map_id:map.id,p_editor_id:editor,p_expected_revision:rev,p_name:map.name,p_document:d,p_request_id:randomUUID()});if(r.ok)rev=r.map.revision;return r;}
 async function report(d){assert.equal((await save(d)).ok,true);return (await rpc('check_map',{p_map_id:map.id})).report;}
 try{
  await t.test('Additive migration can run twice and keeps session/profile',async()=>{user=await callRpc(db,'register_player',{p_username:'tester',p_display_name:'Flo',p_password:'testing42',p_access_code:TEST_ACCESS_CODE});await db.exec(sql);await db.exec(sql);assert.equal((await callRpc(db,'app_status')).editorFeaturesVersion,1);assert.equal((await rpc('get_player_profile')).profile.id,user.profile.id);map=(await rpc('create_map',{p_name:'Neue Mine'})).map;rev=map.revision;await rpc('acquire_map_lock',{p_map_id:map.id,p_editor_id:editor});});
  await t.test('New-format imports compile before their first save',async()=>{const d=fixture();d.rules.unlocks=[{sourceCellId:999,targetCellId:3,number:8}];const created=await rpc('create_map',{p_name:'Direktimport',p_document:d});assert.equal(created.ok,true);assert.deepEqual(created.map.document.rules.unlocks,[{sourceCellId:2,targetCellId:3,number:7}]);await rpc('delete_map',{p_map_id:created.map.id,p_expected_revision:created.map.revision});});
  await t.test('Remote rune requirements including doubles unlock boss attacks automatically',async()=>{const d=fixture();d.rooms.push(cell(11,'rune',80,20,'doubles'),cell(12,'boss',100,40,null,{w:16,h:8,name:'Drache',hits:12,attacks:[{number:8,state:'active'}],rewardFirst:6,rewardLater:0,image:null,imageLayout:null}));const r=await report(d);assert.deepEqual(r.errors,[]);assert.ok(r.rules.unlocks.some(u=>u.sourceCellId===11&&u.targetCellId===12&&u.number==='doubles'));});
  await t.test('Save derives unlocks instead of trusting supplied lists',async()=>{const d=fixture();d.rules.unlocks=[{sourceCellId:999,targetCellId:3,number:8}];assert.equal((await save(d)).ok,true);const stored=(await rpc('get_map',{p_map_id:map.id})).map.document;assert.deepEqual(stored.rules.unlocks,[{sourceCellId:2,targetCellId:3,number:7}]);assert.deepEqual(stored.rules.goals[0].cellIds,[7]);assert.deepEqual(stored.rules.portalPairs,[[4,5]]);});
  await t.test('Portals connect otherwise disconnected areas and path endpoints',async()=>{const r=await report(fixture());assert.deepEqual(r.errors,[]);assert.ok(r.graph.some(e=>e.includes('4')&&e.includes('5')));assert.equal(r.warnings.some(w=>w.cellId==='10'),false);});
  await t.test('Gray fields with closed passage cannot unlock',async()=>{const d=fixture();d.closedDoors['2:3']=true;assert.ok((await report(d)).errors.some(e=>e.cellId==='2'));});
  await t.test('A third portal with the same number cannot publish',async()=>{const d=fixture();d.rooms.push(cell(11,'portal',64,0,9));assert.ok((await report(d)).errors.some(e=>e.cellId==='4'));});
  await t.test('Empty crazy pool, wrong endpoints, nonexistent task target fail publication',async()=>{const d=fixture();d.rooms[5].requirements=[];d.rules.goals[1].cellIds=[1,999];const r=await report(d);assert.ok(r.errors.some(e=>e.cellId==='6'));assert.ok(r.errors.some(e=>e.message.includes('Zielfeld')));});
  await t.test('Invalid pool/negative trap cost/non-enemy defeated image do not bypass draft validation',async()=>{for(const edit of [d=>d.rooms[5].requirements=[3,3],d=>d.rooms[6].trapCost=-1,d=>d.rules.goals[0].reward.first=-1,d=>d.rooms[2].defeatedImage={src:'data:image/png;base64,abc',width:2,height:2,name:'bad'}]){const d=fixture();edit(d);assert.equal((await save(d)).error,'MAP_DOCUMENT_INVALID');}});
  await t.test('Optional bonus cells cannot supply the required end-game enemy',async()=>{const d=fixture();d.rooms[2].type='bonus';d.rooms[1].dimmed=false;assert.ok((await report(d)).errors.some(e=>e.message.includes('Spielende')));});
  await t.test('Defeated art and thumbnail use registered storage refs; large image bounds rejected',async()=>{const path=`${map.id}/${randomUUID()}.png`;await db.query("insert into dungeon_private.assets(path,kind,owner_id,mime_type,bytes) values($1,'map',$2,'image/png',500)",[path,user.profile.id]);const d=fixture();d.rooms[2].defeatedImage={src:`asset:${path}`,width:10,height:10,name:'Troll besiegt'};d.rooms[2].defeatedImageLayout={x:-4,y:0,w:16,h:8};d.previewImage={...d.rooms[2].defeatedImage};assert.equal((await save(d)).ok,true);assert.equal((await rpc('list_maps')).maps[0].previewImage.src,`asset:${path}`);d.rooms[2].defeatedImageLayout.x=-5;assert.equal((await save(d)).error,'MAP_DOCUMENT_INVALID');});
  await t.test('Publication freezes new rules/rewards and portal graph; online creation is gated',async()=>{assert.deepEqual((await report(fixture())).errors,[]);const p=await rpc('publish_map',{p_map_id:map.id,p_editor_id:editor,p_expected_revision:rev,p_accept_warnings:true});assert.equal(p.ok,true,JSON.stringify(p));const v=(await db.query('select * from dungeon_map_versions where id=$1',[p.map.versionId])).rows[0];assert.equal(v.definition_version,2);assert.deepEqual(v.rules.goals[0].reward,{first:5,later:2});assert.ok(v.compiled_graph.some(e=>e.includes('4')&&e.includes('5')));assert.equal((await rpc('create_game',{p_map_version_id:v.id,p_name:'Zu früh',p_settings:{maxPlayers:4,cards:'open',hints:true},p_password:'',p_request_id:randomUUID()})).error,'GAME_MAP_UNAVAILABLE');assert.equal((await rpc('list_game_maps')).maps.length,0);});
  await t.test('Old published maps still create games after the upgrade',async()=>{const legacy=emptyDocument();legacy.rooms=[cell(1,'normal',0,0,7,{start:true}),cell(2,'monster',4,0,null,{name:'Troll',hits:2,attacks:[{number:7,state:'active'}],rewardFirst:3,rewardLater:1,image:null,imageLayout:null})];const p=await publishFixture(db,user,'Alte Welt',legacy);assert.equal((await rpc('list_game_maps')).maps.length,1);assert.equal((await rpc('create_game',{p_map_version_id:p.versionId,p_name:'Weiter',p_settings:{maxPlayers:4,cards:'open',hints:true},p_password:'',p_request_id:randomUUID()})).ok,true);});
 }finally{await db.close();}
});
