// Echte Desktop-/Handybrowser und isoliertes PostgreSQL. Keine Live-Schreibzugriffe.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createRequire} from 'node:module';import {mkdir} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';
import {createUpgradedDatabase,modernFixture} from './helpers/game-upgrade.mjs';import {register,userRpc,publishFixture} from './helpers/games.mjs';import {callRpc} from './helpers/database.mjs';import {installTestDice,forceDice,newPlayGame,seedState} from './helpers/turns.mjs';import {goalDefault} from '../web/js/maps/features.js';import {CONFIG} from '../web/js/config.js';

const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../',import.meta.url)),address='http://localhost:5196';
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,PORT:'5196'},stdio:'ignore'}),db=await createUpgradedDatabase(),sockets=new Set(),errors=[],requests=[],images=new Map();
let queue=Promise.resolve(),lastSignal=0,browser,page,phone,checks=0,assetReads=0,dropTurn=false;
const serial=fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;};
const check=(value,label)=>{assert.ok(value,label);checks++;console.log(`PASS ${label}`);};
async function signals(){for(const s of (await db.query('select * from realtime.test_signals where id>$1 order by id',[lastSignal])).rows){lastSignal=s.id;for(const socket of sockets)if(socket.topics.has(`realtime:${s.topic}`))socket.ws.send(JSON.stringify({topic:`realtime:${s.topic}`,event:'broadcast',payload:{type:'broadcast',event:'changed',payload:s.payload},ref:null}));}}
async function rpc(user,name,args={}){return serial(async()=>{const data=await userRpc(db,user,name,args);await signals();return data;});}
async function gateway(context){
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await context.routeWebSocket(url=>url.href.startsWith(CONFIG.supabaseUrl.replace('https:','wss:')+'/realtime/'),ws=>{
  const socket={ws,topics:new Set()};sockets.add(socket);ws.onClose(()=>sockets.delete(socket));ws.onMessage(text=>{const m=JSON.parse(text.toString());if(m.event==='phx_join'){socket.topics.add(m.topic);ws.send(JSON.stringify({topic:m.topic,event:'phx_reply',ref:m.ref,join_ref:m.join_ref,payload:{status:'ok',response:{}}}));}else if(m.event==='heartbeat')ws.send(JSON.stringify({topic:'phoenix',event:'phx_reply',ref:m.ref,payload:{status:'ok',response:{}}}));});
 });
 await context.route(`${CONFIG.supabaseUrl}/**`,async route=>{
  const req=route.request(),url=new URL(req.url()),headers={'access-control-allow-origin':'*','access-control-allow-methods':'POST,GET,OPTIONS','access-control-allow-headers':'apikey,content-type,x-session-token'};
  if(req.method()==='OPTIONS'){await route.fulfill({status:204,headers});return;}
  if(url.pathname.startsWith('/storage/v1/object/public/map-assets/')){assetReads++;const img=images.get(url.pathname.split('/map-assets/')[1]);await route.fulfill({status:img?200:404,headers:{...headers,'content-type':'image/png'},body:img||''});return;}
  const method=url.pathname.split('/').at(-1),args=req.postDataJSON();requests.push({method,args});
  try{const data=await serial(async()=>{const answer=await callRpc(db,method,args);await signals();return answer;});if(dropTurn&&method==='play_game_action'&&data.ok){dropTurn=false;await route.abort('failed');return;}await route.fulfill({status:200,headers,body:JSON.stringify(data)});}catch(e){await route.fulfill({status:400,headers,body:JSON.stringify({message:e.message})});}
 });
}
async function login(p,name){await p.goto(address);await p.locator('#auth-form').waitFor();await p.fill('#username',name);await p.fill('#password','testing42');await p.click('#auth-submit');await p.locator('.home-view').waitFor();}
async function open(p,id,lobby=false){await p.goto(address+`/#/game?id=${id}`);await p.locator(lobby?'#start-game':'#game-board-svg').waitFor({timeout:25000});}
const cell=(p,id)=>p.locator(`#gameTargets [data-cell-id="${id}"]`);
async function play(p,id){await p.waitForFunction(id=>document.querySelector(`#gameTargets [data-cell-id="${id}"]`)?.getAttribute('aria-disabled')==='false',String(id));await cell(p,id).focus();await cell(p,id).press('Enter');}
async function refresh(p){await Promise.all([p.waitForResponse(r=>r.url().endsWith('/rpc/get_game')&&r.status()===200),p.evaluate(()=>document.querySelector('#refresh-game').click())]);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
const get=async(u,id)=>(await rpc(u,'get_game',{p_game_id:id})).game;
async function acknowledge(p){const d=p.locator('.life-loss-dialog');if(await d.count())await d.getByRole('button',{name:'Verstanden'}).click();}
try{
 await installTestDice(db);const flo=await register(db,'Flo'),joni=await register(db,'Joni');await mkdir(root+'/test-results',{recursive:true});
 for(let i=0;i<100;i++){try{if((await fetch(address)).ok)break;}catch{}await new Promise(r=>setTimeout(r,30));}
 let args=[];if(process.env.WUERFELDUNGEON_CHROMIUM_MODULE)args=require(process.env.WUERFELDUNGEON_CHROMIUM_MODULE).default.args.filter(v=>!['--single-process','--disable-web-security'].includes(v));
 browser=await chromium.launch({headless:true,executablePath:process.env.WUERFELDUNGEON_CHROMIUM_PATH||undefined,args});
 const desktop=await browser.newContext({viewport:{width:1440,height:1040}}),mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await gateway(desktop);await gateway(mobile);page=await desktop.newPage();phone=await mobile.newPage();
 async function image(color,name){const png=Buffer.from(await page.evaluate(color=>{const c=document.createElement('canvas');c.width=96;c.height=96;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.beginPath();ctx.arc(48,48,36,0,Math.PI*2);ctx.fill();return c.toDataURL('image/png').split(',')[1];},color),'base64');const path=`${randomUUID()}/${randomUUID()}.png`;images.set(path,png);await db.query("insert into dungeon_private.assets(path,kind,owner_id,mime_type,bytes) values($1,'map',$2,'image/png',$3)",[path,flo.profile.id,png.length]);return {src:`asset:${path}`,width:96,height:96,name};}
 const alive=await image('#9dba7d','Troll'),dead=await image('#998474','Besiegter Troll'),background=await image('#f1ece1','Hintergrund');
 const d=modernFixture();d.background={x:-4,y:-4,w:76,h:24,image:background};d.rooms.find(r=>r.id===3).image=alive;d.rooms.find(r=>r.id===3).imageLayout={x:-1,y:0,w:10,h:8};d.rooms.find(r=>r.id===3).defeatedImage=dead;d.rooms.find(r=>r.id===3).defeatedImageLayout={x:0,y:0,w:8,h:8};d.rules.goals=[{...goalDefault(),type:'allType',fieldType:'trap',reward:{first:4,later:2}},{...goalDefault(),type:'connect',cellIds:[1,11],reward:{first:5,later:0}}];
 const map=await publishFixture(db,flo,'Nebelmine',d);await login(page,'flo');await login(phone,'joni');
 await page.goto(address+'/#/new-game');await page.locator('.game-map-choice').waitFor();await page.locator('.game-map-choice').click();check(await page.locator('#game-fog').count()===1&&await page.locator('#game-dice-hints').count()===1&&await page.locator('#game-field-hints').count()===1,'Fog und beide Tipps getrennt in der echten Spielauswahl');await page.check('#game-fog');await page.uncheck('#game-field-hints');await page.click('#create-game');await page.locator('#start-game').waitFor();
 check((await page.locator('.lobby-rules').textContent()).includes('Ab der Runde')&&(await page.locator('.lobby-rules').textContent()).includes('Bonusaufgaben'),'Warteraum erklärt Spezialfelder und individuelle Aufgaben');check((await page.locator('.lobby-rules').textContent()).includes('4 ♦ zuerst / 2 ♦ später'),'Warteraum zeigt die tatsächlichen Belohnungen');
 const created=requests.filter(r=>r.method==='create_game').at(-1),lobby=(await rpc(flo,'list_games')).lobbies[0];check(created.args.p_settings.diceHints&&created.args.p_settings.fieldHints===false&&created.args.p_settings.fog,'Getrennte Optionen werden gespeichert');await rpc(joni,'join_game',{p_game_id:lobby.id,p_password:'',p_request_id:randomUUID()});await refresh(page);await page.click('#start-game');await page.locator('#game-board-svg').waitFor();await open(phone,lobby.id);
 check(await cell(page,6).getAttribute('visibility')==='hidden'&&await cell(phone,6).getAttribute('tabindex')==='-1','Nebel verdeckt entfernte Felder und nimmt sie aus der Tastaturauswahl');check(await page.locator('.game-fog').count()>=1,'Dichter Nebel liegt über Hintergrund und Feldern');
 const id=lobby.id;await serial(()=>forceDice(db,[2,4,1,1]));await page.click('#roll-dice');await phone.locator('#game-dice').waitFor();check(await page.locator('.combination-list').count()===1&&await page.locator('.legal-cell').count()===0,'Nur Würfelsummen aktiviert: kein Feld wird hervorgehoben');await play(page,1);await play(phone,1);await phone.locator('#roll-dice').waitFor();
 // Mit echten Realtime-Updates die gespeicherte Rundenzahl und Portal-Markierung prüfen.
 const round=(await get(flo,id)).round;await serial(()=>forceDice(db,[4,5,1,1]));await phone.click('#roll-dice');await play(phone,4);await phone.locator('#game-board-svg [data-marked-cell="5"]').waitFor();await play(page,4);await page.locator('#roll-dice').waitFor();
 check(await cell(page,6).getAttribute('visibility')==='visible'&&await page.locator('#game-board-svg [data-marked-cell="4"]').count()===1,'Portal legt beide Felder frei und vergrößert die persönliche Sicht');
 const g=await get(flo,id);check(g.round===round+1&&await page.locator('#game-board-svg [data-crazy-value]').getAttribute('data-number')===String(g.roundRequirements['6']),'Zufallsfeld zeigt die gespeicherte Zahl der neuen Runde');
 check(await page.locator('.opponent-miniature .game-fog').count()===1&&await page.locator('.opponent-miniature .room[data-id="9"]').getAttribute('visibility')==='hidden','Gegner-Miniatur bewahrt ihren eigenen Nebel');
 await page.locator('.opponent-miniature').click();await page.locator('#opponent-board-svg').waitFor();check(await page.locator('#opponent-board-svg .game-fog').count()===1,'Auch vergrößerte Gegnerkarte bleibt im Nebel');await page.locator('.opponent-dialog').getByRole('button',{name:'Schließen',exact:true}).click();
 // Fernglas aus echter Truhenauswahl, inklusive dauerhafter Sicht und Wiederverbinden.
 await serial(()=>seedState(db,id,flo,{reached:['5'],pendingChests:['13']}));await refresh(page);await page.locator('[data-powerup="binocular"]').click();await page.locator('.powerup-dialog').waitFor({state:'detached'});check((await get(flo,id)).ownState.visionRadius===3&&await cell(page,8).getAttribute('visibility')==='visible','Fernglas aktiviert dauerhaft die dritte Entfernung');await page.reload();await page.locator('#game-board-svg').waitFor();check(await cell(page,8).getAttribute('visibility')==='visible'&&(await page.locator('.score-vision').textContent()).includes('3'),'Fernglas bleibt nach Reload erhalten');
 // Bekämpfte/besiegte Bilder pro Spieler, stabiler DOM und gleiche Erstbelohnung.
 const combat=await serial(()=>newPlayGame(db,[flo,joni],{cards:'open',fog:false},map));for(const u of [flo,joni])await serial(()=>seedState(db,combat,u,{reached:['2'],monsterHits:{3:1}}));await open(page,combat);await open(phone,combat);await page.locator('.opponent-miniature').waitFor();
 const imageNode=page.locator('#enemyImagesLayer .enemy-image[data-id="3"] image'),liveSrc=await imageNode.getAttribute('href');await page.evaluate(()=>{window.__sprite=document.querySelector('#enemyImagesLayer .enemy-image[data-id="3"] image');window.__board=document.querySelector('#game-board-svg');window.__mini=document.querySelector('.opponent-miniature svg');});const reads=assetReads;await refresh(page);await refresh(page);check(assetReads===reads&&await page.evaluate(()=>window.__sprite===document.querySelector('#enemyImagesLayer .enemy-image[data-id="3"] image')&&window.__board===document.querySelector('#game-board-svg')),'Unveränderte Updates bewahren SVG und Bilder ohne neue Downloads');
 await serial(()=>forceDice(db,[4,4,1,2]));await page.click('#roll-dice');await phone.locator('#game-dice').waitFor();dropTurn=true;await play(phone,3);await phone.waitForFunction(()=>document.querySelector('#enemyImagesLayer .enemy-image[data-id="3"] image')?.getAttribute('data-defeated')==='true');
 check(await imageNode.getAttribute('href')===liveSrc&&(await get(joni,combat)).ownState.diamonds===3,'Bildwechsel ist persönlich; erster Sieg bekommt drei Diamanten');await play(page,3);await page.waitForFunction(()=>document.querySelector('#enemyImagesLayer .enemy-image[data-id="3"] image')?.getAttribute('data-defeated')==='true');check(await imageNode.getAttribute('href')!==liveSrc&&await page.evaluate(()=>window.__sprite===document.querySelector('#enemyImagesLayer .enemy-image[data-id="3"] image')),'Besiegtes Bild wechselt im bestehenden Bildknoten und nutzt seine eigene Größe');check((await get(flo,combat)).ownState.diamonds===3&&(await get(joni,combat)).ownState.diamonds===3,'Beide Spieler bekommen bei Sieg in derselben Runde die Erstbelohnung');check(await page.evaluate(()=>window.__mini===document.querySelector('.opponent-miniature svg')),'Gegnerminiatur bleibt beim Bildwechsel im DOM');
 const turns=requests.filter(r=>r.method==='play_game_action'&&r.args.p_cell_id==='3'),counts=new Map();for(const r of turns)counts.set(r.args.p_request_id,(counts.get(r.args.p_request_id)||0)+1);check(turns.length===3&&[...counts.values()].includes(2),'Verlorene Zugantwort wiederholt denselben Befehl ohne doppelte Belohnung');
 // Aktive Fallen und klare Verlustmeldung auf dem Handy.
 const traps=await serial(()=>newPlayGame(db,[flo,joni],{cards:'hidden'},map));for(const u of [flo,joni])await serial(()=>seedState(db,traps,u,{reached:['14']}));await open(page,traps);await open(phone,traps);await serial(()=>forceDice(db,[4,5,1,1]));await page.click('#roll-dice');await play(page,15);await serial(()=>db.query("update dungeon_games set choice_started_at=now()-interval '61 seconds' where id=$1",[traps]));await rpc(flo,'resolve_game_wait',{p_game_id:traps,p_round:1,p_target_player_id:joni.profile.id,p_action:'skip',p_request_id:randomUUID()});await refresh(phone);await phone.locator('#roll-dice').waitFor();check(await phone.locator('#roomsLayer .room[data-id="15"] [data-trap-armed]').count()===1,'Falle wird erst ab der folgenden Runde als scharf dargestellt');await serial(()=>forceDice(db,[4,5,1,1]));await phone.click('#roll-dice');await play(phone,15);await phone.locator('.life-loss-dialog').waitFor();check((await phone.locator('.life-loss-dialog').textContent()).includes('2 Leben verloren')&&await phone.locator('.life-box.lost').count()===2,'Lebensfalle füllt zwei Kästchen und zeigt eine Bestätigung');await acknowledge(phone);
 await page.screenshot({path:root+'/test-results/rules-desktop.png',fullPage:true});await phone.screenshot({path:root+'/test-results/rules-handy.png',fullPage:true});check(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Neue Aufgaben, Meldungen und Punkte passen auf die Handybreite');check(errors.length===0,'Keine JavaScript-Fehler in beiden Browsern');console.log(`${checks} Online-Regeln-Browserprüfungen erfolgreich.`);
}catch(e){console.error(e.message);await page?.screenshot({path:root+'/test-results/rules-error.png',fullPage:true}).catch(()=>{});throw e;}finally{await browser?.close();server.kill();await queue;await db.close();}
