import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler,validImage} from '../supabase/functions/map-asset-upload/index.ts';
const token='a'.repeat(64),mapId='11111111-1111-4111-8111-111111111111',editorId='22222222-2222-4222-8222-222222222222',secret='sb_secret_local_test_only';
const png=Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1]);
const env=name=>({SUPABASE_URL:'https://test.supabase.co',SUPABASE_SECRET_KEYS:JSON.stringify({default:secret})})[name];
function request(file=new Blob([png],{type:'image/png'})){const form=new FormData();form.append('file',file,'image.png');form.append('mapId',mapId);form.append('editorId',editorId);return new Request('https://test.example',{method:'POST',headers:{'x-session-token':token},body:form});}
function mock(log,{locked=false,uncertain=false,commitDenied=false}={}){return async(url,opts)=>{log.push({url,opts});if(url.includes('validate_player_session'))return Response.json({ok:true});if(url.includes('app_authorize_map_asset'))return Response.json(locked?{ok:false,error:'MAP_LOCK_LOST'}:{ok:true});if(url.includes('app_finish_map_asset')){if(uncertain)throw Error('Network');return Response.json(commitDenied?{ok:false,error:'MAP_LOCK_LOST'}:{ok:true,path:`${mapId}/${editorId}.png`});}return Response.json({ok:true});};}
test('Kartenbilder: PNG/JPEG/WebP Signaturen und falsche Formate',()=>{assert.equal(validImage(png,'image/png'),true);assert.equal(validImage(png,'image/jpeg'),false);assert.equal(validImage(new Uint8Array(30),'image/png'),false);});
test('Kartenbilder: Sitzung und genaue Editor-Sperre müssen vor jedem Upload stimmen',async()=>{const log=[],handler=createHandler({env,fetcher:mock(log,{locked:true})});const result=await handler(request());assert.equal(result.status,409);assert.equal(log.length,2);});
test('Kartenbilder: Server erzeugt Pfad; privater Schlüssel bleibt auf dem Server',async()=>{const log=[],handler=createHandler({env,fetcher:mock(log),uuid:()=>editorId});const result=await handler(request());assert.equal(result.status,200);assert.equal((await result.json()).path,`${mapId}/${editorId}.png`);assert.equal(log[2].opts.headers.Authorization,undefined);assert.equal(log[2].opts.headers.apikey,secret);assert.equal(log.length,4);});
test('Kartenbilder: Falsche Datei wird vor Storage abgelehnt',async()=>{const log=[],handler=createHandler({env,fetcher:mock(log)});assert.equal((await handler(request(new Blob(['bad'],{type:'image/png'})))).status,400);assert.equal(log.length,2);});
test('Kartenbilder: Sperrverlust beim Abschluss entfernt neues Objekt',async()=>{const log=[],handler=createHandler({env,fetcher:mock(log,{commitDenied:true})});assert.equal((await handler(request())).status,409);assert.equal(log.at(-1).opts.method,'DELETE');});
test('Kartenbilder: Unklarer Abschluss entfernt kein eventuell bereits registriertes Objekt',async()=>{const log=[],handler=createHandler({env,fetcher:mock(log,{uncertain:true})});assert.equal((await handler(request())).status,503);assert.equal(log.length,4);});
