import test from 'node:test';import assert from 'node:assert/strict';
import {visibleCells,viewVisibility} from '../web/js/games/visibility.js';
import {TestGame} from '../web/js/games/test-engine.js';
import {cleanPreferences} from '../web/js/validation.js';
import {modernFixture} from './helpers/game-upgrade.mjs';
import {compileDocument} from '../web/js/maps/features.js';
import {connections} from '../web/js/maps/model.js';
const field=(id,type='normal',more={})=>({id,type,x:(id-1)*4,y:0,w:4,h:4,number:8,start:id===1,hits:2,attacks:[{number:8,state:'active'}],rewardFirst:3,...more});
const line=()=>({document:{rooms:[field(1),field(2,'monster'),field(3),field(4),field(5)]},graph:[['1','2'],['2','3'],['3','4'],['4','5']],rules:{}});
test('Sicht folgt Graph, stoppt an Gegnern und bleibt mit Fernglas blockiert',()=>{const d=line();assert.deepEqual(visibleCells(d,{reached:['1']}),['1','2']);assert.deepEqual(visibleCells(d,{reached:['1'],powerups:['binocular']}),['1','2']);assert.deepEqual(visibleCells(d,{reached:['1','2']}),['1','2','3','4']);assert.ok(visibleCells(d,{reached:['1','2'],powerups:['binocular']}).includes('5'));d.document.rooms[1].type='bonus';assert.ok(visibleCells(d,{reached:['1']}).includes('3'));});
test('Horn enthüllt nur Gegner und endet nach zehn Sekunden',()=>{const d=line();d.document.rooms[4].type='boss';const s={reached:['1'],hornUntil:'2026-10-03T10:00:10Z'};assert.deepEqual(viewVisibility(d,s,['1','2'],Date.parse('2026-10-03T10:00:05Z')),['1','2','5']);assert.deepEqual(viewVisibility(d,s,['1','2'],Date.parse('2026-10-03T10:00:11Z')),['1','2']);});
test('Erreichte Portale zählen zur Sicht, entfernte Räume ohne Verbindung nicht',()=>{const d=line();d.rules.portalPairs=[[1,5]];assert.ok(visibleCells(d,{reached:['1']}).includes('5'));d.document.rooms.push(field(9));assert.ok(!visibleCells(d,{reached:['1']}).includes('9'));});
test('Testmodus hat echte Phasen, legale Linksklicks, freie einzelne Rechtsklick-Hits und einmalige Belohnungen',()=>{const d=line(),g=new TestGame(d);assert.throws(()=>g.play(1));g.roll([4,4,3,5]);g.play(1);assert.throws(()=>g.play(3));g.play(3,{cheat:true});assert.ok(g.reached(3));assert.equal(g.phase,'waiting_roll');g.play(2,{cheat:true});assert.equal(g.state.monsterHits[2],1);assert.equal(g.state.diamonds,0);g.play(2,{cheat:true});assert.equal(g.state.monsterHits[2],2);assert.equal(g.state.diamonds,3);g.play(2,{cheat:true});assert.equal(g.state.diamonds,3);assert.deepEqual(d.document.rooms,line().document.rooms);g.reset();assert.equal(g.state.diamonds,0);assert.deepEqual(g.state.reached,[]);});
test('Fackel kann Monster als Ziel nutzen, Gegner nicht als Zwischenraum; Portal-Ausgang nutzbar',()=>{const d=line(),g=new TestGame(d);d.document.rooms[1].type='normal';const h=new TestGame(d);h.state.reached=['1'];h.state.torchUses=2;h.roll([4,4,3,5]);assert.ok(h.torchActions().some(a=>a.cellId==='3'&&a.middleCellId==='2'));h.play(3,{middle:'2'});assert.ok(h.reached('2')&&h.reached('3'));assert.equal(h.state.torchUses,1);g.state.reached=['1'];g.state.torchUses=2;g.roll([4,4,3,5]);assert.ok(!g.torchActions().some(a=>a.middleCellId==='2'));});
test('Test-Powerups, Schätze, negative Fallen und Aufgaben bleiben nur im lokalen Stand',()=>{const raw=compileDocument(modernFixture()),g=new TestGame({document:raw,rules:raw.rules,allowedPowerups:[...raw.allowedPowerups,'horn'],graph:connections(raw)});g.play(13,{cheat:true});g.choosePower('torch');assert.equal(g.state.torchUses,2);g.enablePower('horn');g.horn();assert.equal(g.state.hornUses,0);assert.ok(Date.parse(g.state.hornUntil)>Date.now());g.enablePower('extraLife');g.enablePower('extraLife');assert.equal(g.state.diamonds,1);g.traps.set('7',0);g.round=2;g.play(7,{cheat:true});assert.equal(g.state.diamonds,-1);g.play(9,{cheat:true});g.play(10,{cheat:true});assert.equal(g.state.goldPoints,3);g.play(4,{cheat:true});assert.ok(g.reached(5));});
test('Neue kosmetische Vorlieben sind optional; alte vier Schlüssel bleiben unverändert',()=>{const old={markStyle:'cross',sound:true,music:false,reduceMotion:false};assert.deepEqual(cleanPreferences(old),old);const p=cleanPreferences({...old,diceStyle:'midnight',cupStyle:'runic',campStyle:'moon',diceAnimation:'long'});assert.equal(p.diceStyle,'midnight');assert.equal(cleanPreferences({...old,diceStyle:'bogus'}).diceStyle,'ivory');});

test('Fackel schaltet über grauen Zwischenraum die passende Monsterzahl sofort frei',()=>{const d=line();d.document.rooms[1].type='normal';d.document.rooms[1].dimmed=true;d.document.rooms[2].type='monster';d.document.rooms[2].attacks=[{number:8,state:'locked'}];d.rules.unlocks=[{sourceCellId:2,targetCellId:3,number:8}];const g=new TestGame(d);g.state.reached=['1'];g.state.torchUses=2;g.roll([4,4,1,2]);assert.ok(g.torchActions().some(a=>a.cellId==='3'&&a.middleCellId==='2'));g.play(3,{middle:2});assert.equal(g.state.monsterHits[3],1);assert.ok(g.reached(2));});
