import {createHandler} from '../supabase/functions/map-asset-upload/index.ts';
// Browserprüfung mit echter isolierter SQL-Datenbank. Kein Zugriff auf Live-Daten.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createRequire} from 'node:module';import {readFile,mkdir,writeFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';
import {createShopDatabase} from './helpers/shop.mjs';import {modernFixture} from './helpers/game-upgrade.mjs';import {register,userRpc,publishFixture} from './helpers/games.mjs';import {newPlayGame,installTestDice,forceDice} from './helpers/turns.mjs';import {callRpc} from './helpers/database.mjs';import {CONFIG} from '../web/js/config.js';import {compileDocument} from '../web/js/maps/features.js';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../',import.meta.url)),url='http://localhost:5201';
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,PORT:'5201'},stdio:'ignore'});let browser,db,page,queue=Promise.resolve(),checks=0,phase='setup';const errors=[],requests=[],images=new Map();
const watchdog=setTimeout(()=>{console.error(`WATCHDOG: ${phase}`);server.kill();process.exit(1);},240000);
const serial=fn=>{const job=queue.then(fn);queue=job.catch(()=>{});return job;},check=(v,label)=>{assert.ok(v,label);checks++;console.log('PASS',label);};
const rpc=(u,name,args={})=>serial(()=>userRpc(db,u,name,args));
async function refresh(){await page.locator('#refresh-game').click();await page.waitForTimeout(150);}
const upload=createHandler({env:name=>({SUPABASE_URL:CONFIG.supabaseUrl,SUPABASE_SECRET_KEYS:JSON.stringify({default:'sb_secret_local_test_only'})})[name],fetcher:async(url,opts)=>{
 const path=new URL(url).pathname;
 if(path.startsWith('/rest/')){try{return Response.json(await serial(()=>callRpc(db,path.split('/').at(-1),JSON.parse(opts.body),'service_role')));}catch(e){return Response.json({message:e.message},{status:400});}}
 if(opts.method==='DELETE'){for(const p of JSON.parse(opts.body).prefixes)images.delete(p);return Response.json({ok:true});}
 images.set(path.replace('/storage/v1/object/map-assets/',''),Buffer.from(opts.body));return Response.json({ok:true});
}});
async function gateway(context){context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));await context.route(`${CONFIG.supabaseUrl}/**`,async route=>{
 const req=route.request(),path=new URL(req.url()).pathname,headers={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'apikey,content-type,x-session-token'};
 if(req.method()==='OPTIONS'){await route.fulfill({status:204,headers});return;}
 if(path.includes('/storage/v1/object/public/map-assets/')){const img=images.get(path.split('/map-assets/')[1]);await route.fulfill({status:img?200:404,headers:{...headers,'content-type':'image/png'},body:img||''});return;}
 if(path==='/functions/v1/map-asset-upload'){const r=await upload(new Request(req.url(),{method:req.method(),headers:req.headers(),body:req.postDataBuffer()}));await route.fulfill({status:r.status,headers,body:await r.text()});return;}
 const method=path.split('/').at(-1),args=req.postDataJSON();requests.push(method);try{const result=await serial(()=>callRpc(db,method,args));if(method==='app_status')result.realtimeAvailable=false;await route.fulfill({status:200,headers,body:JSON.stringify(result)});}catch(error){await route.fulfill({status:400,headers,body:JSON.stringify({message:error.message})});}
});}
async function login(user){await page.goto(url);await page.getByRole('tab',{name:'Anmelden'}).click();await page.locator('#username').fill(user.profile.username);await page.locator('#password').fill('testing42');await page.locator('#auth-submit').click();await page.waitForURL('**/#/home');}
async function image(user,name,first,second){const data=await page.evaluate(({first,second})=>{const c=document.createElement('canvas');c.width=640;c.height=320;const x=c.getContext('2d'),g=x.createLinearGradient(0,0,640,320);g.addColorStop(0,first);g.addColorStop(1,second);x.fillStyle=g;x.fillRect(0,0,640,320);return c.toDataURL('image/png');},{first,second});const path=`${randomUUID()}/${randomUUID()}.png`,bytes=Buffer.from(data.split(',')[1],'base64');images.set(path,bytes);await db.query("insert into dungeon_private.assets(path,kind,owner_id,mime_type,bytes) values($1,'map',$2,'image/png',$3)",[path,user.profile.id,bytes.length]);return {src:`asset:${path}`,name,width:640,height:320};}
try{
 db=await createShopDatabase();await db.exec(await readFile(root+'/supabase/migrations/020_round_two.sql','utf8'));await installTestDice(db);const a=await register(db,'Browserflo'),b=await register(db,'Browserjoni');
 for(let i=0;i<100;i++){try{if((await fetch(url)).ok)break;}catch{}await new Promise(r=>setTimeout(r,30));}
 let args=[];if(process.env.WUERFELDUNGEON_CHROMIUM_MODULE)args=require(process.env.WUERFELDUNGEON_CHROMIUM_MODULE).default.args.filter(v=>!['--single-process','--disable-web-security'].includes(v));browser=await chromium.launch({headless:true,executablePath:process.env.WUERFELDUNGEON_CHROMIUM_PATH||undefined,args});const context=await browser.newContext({viewport:{width:1366,height:768}});await gateway(context);page=await context.newPage();page.setDefaultTimeout(18000);await login(a);
 if(!process.argv.includes('--editor-only')){phase='settings';await page.goto(url+'/#/settings');await page.locator('#diceStyle-midnight').check();await page.locator('#cupStyle-runic').check();await page.locator('#campStyle-moon').check();await page.locator('#diceAnimation').fill('3');await page.locator('#diceAnimation').dispatchEvent('input');await page.locator('#sound').uncheck();await page.locator('#music').check();await page.locator('#save-settings').click();await page.waitForFunction(()=>document.querySelector('.feedback.success')?.textContent.includes('gespeichert'));
 const prefs=(await rpc(a,'get_player_profile')).profile.preferences;check(prefs.campStyle==='moon'&&prefs.diceAnimation==='long'&&!prefs.sound&&prefs.music,'Kosmetische Vorlieben und getrennte Audio-Schalter gespeichert');check(await page.locator('.forest').getAttribute('src')==='./assets/forest-moon.svg','Lagerhintergrund nutzt native neue Variante');check(await page.locator('[data-shop-category="markStyle"] .mark-option').count()===10,'Zehn Markierungen im Shop');
 const audioCheck=await page.evaluate(async()=>{const {audio}=await import('./js/audio.js');audio.unlock();audio.configure({sound:false,music:true});const background=audio.ambient.length>0;const original=audio.tone;let calls=0;audio.tone=()=>calls++;audio.effect('victory');const quiet=calls===0;audio.configure({sound:true,music:false});const stopped=audio.ambient.length===0;audio.effect('victory');const effects=calls>0;audio.tone=original;audio.configure({sound:false,music:false});return background&&quiet&&stopped&&effects;});check(audioCheck,'Audio-Effekte und Hintergrundklang arbeiten unabhängig');
 }
 if(process.argv.includes('--editor-only')){const current=(await rpc(a,'get_player_profile')).profile;await rpc(a,'update_player_preferences',{p_preferences:{...current.preferences,music:true},p_expected_revision:current.revision});await page.reload();}
 const d=compileDocument(modernFixture());d.allowedPowerups.push('horn');d.background={x:-8,y:-8,w:84,h:32,image:await image(a,'Mine','#294537','#bd8048')};d.rooms.find(r=>r.id===3).image=await image(a,'Troll','#7ea461','#718064');d.rooms.find(r=>r.id===3).defeatedImage=await image(a,'Troll besiegt','#7e8162','#b7ad7e');const map=await publishFixture(db,a,'Browsermine',d);
 if(!process.argv.includes('--online-only')){
 phase='editor';const created=await rpc(a,'create_map',{p_name:'Lokale Testmine'}),id=created.map.id,editorId=randomUUID();let lock=await rpc(a,'acquire_map_lock',{p_map_id:id,p_editor_id:editorId});check((await rpc(a,'save_map',{p_map_id:id,p_editor_id:editorId,p_expected_revision:lock.map.revision,p_name:'Lokale Testmine',p_document:d,p_request_id:randomUUID()})).ok,'Testentwurf vorbereitet');await rpc(a,'release_map_lock',{p_map_id:id,p_editor_id:editorId});await page.goto(url+`/#/editor?id=${id}`);await page.locator('#test-map').waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('#test-map').disabled);const beforeGames=Number((await db.query('select count(*) from dungeon_games')).rows[0].count),beforeRequests=requests.length;
 await page.locator('#test-map').click();await page.locator('#test-board-svg .game-cell-target').first().waitFor();await page.locator('#test-board-svg [data-cell-id="3"]').click({button:'right',force:true});await page.waitForFunction(()=>document.querySelectorAll('#test-board-svg .enemy-info[data-id="3"] [data-hit][fill="#375b48"]').length===1);await page.locator('#test-board-svg [data-cell-id="3"]').click({button:'right',force:true});await page.waitForFunction(()=>document.querySelectorAll('#test-board-svg .enemy-info[data-id="3"] [data-hit][fill="#375b48"]').length===2);check((await page.locator('#test-score').textContent()).includes('3 ♦'),'Freie Rechtsklick-Angriffe geben lokale Belohnung');
 await page.locator('#test-fog').check();await page.getByText('Powerups frei ausprobieren',{exact:true}).click();await page.locator('[data-test-power="horn"]').check();await page.locator('#test-horn').click();check(await page.locator('#test-board-svg .game-fog').count()===1,'Testnebel und Horn verfügbar');check(Number((await db.query('select count(*) from dungeon_games')).rows[0].count)===beforeGames&&!requests.slice(beforeRequests).some(n=>['create_game','play_game_action','roll_game_dice','choose_game_powerup'].includes(n)),'Testmodus schreibt keine Spiele, Züge oder Belohnungen');await page.getByRole('button',{name:'Test schließen'}).click();
 phase='cell-picker';await page.locator('#map-rules').click();await page.locator('#goal-1-type').selectOption('connect');await page.getByRole('button',{name:'Felder auf Karte auswählen'}).first().click();await page.locator('#picker-board-svg .game-cell-target').first().waitFor();await page.locator('#picker-board-svg [data-cell-id="1"]').click({force:true});await page.locator('#picker-board-svg [data-cell-id="11"]').click({force:true});await page.locator('.rules-dialog[open]').waitFor();check(await page.locator('.cell-picker-dialog').count()===0,'Grafische Feldauswahl kehrt nach zwei Endpunkten zurück');await page.locator('#save-map-rules').click();await page.locator('#save-map').click();await page.waitForFunction(()=>document.querySelector('#map-save-status')?.textContent.startsWith('Gespeichert'));const saved=(await rpc(a,'get_map',{p_map_id:id})).map.document;check(JSON.stringify(saved.rules.goals[0].cellIds)==='[1,11]','Grafische Zielfelder werden als IDs gespeichert');await page.locator('#check-publish-map').click();await page.locator('.rules-dialog[open]').waitFor();check(await page.locator('.publish-dialog').count()===0,'Veröffentlichen öffnet zuerst die Regelübersicht');await page.locator('.rules-dialog[open]').getByRole('button',{name:'Abbrechen'}).click();
 await mkdir(root+'/test-results',{recursive:true});const preview=await page.locator('#dungeon-editor').evaluate(async frame=>frame.contentWindow.DungeonEditor.exportPreview());await writeFile(root+'/test-results/round-two-editor.png',Buffer.from(preview.src.split(',')[1],'base64'));check(preview.width>0&&preview.height>0,'PNG-Vorschau mit Hintergrund und neuem Feldstil exportiert');
 }
 if(process.argv.includes('--editor-only')){check(errors.length===0,`Keine Editor-JavaScript-Fehler: ${errors.join('; ')}`);console.log(`TOTAL ${checks} Editor-Browserprüfungen bestanden.`);process.exitCode=0;}else{
 phase='new-game';await page.goto(url+'/#/new-game');await page.locator('#game-map-selection button').first().waitFor();await page.locator('#game-map-selection button').first().click();await page.locator('#game-fog').check();await page.locator('.fog-preview img').first().waitFor();check(await page.locator('#game-cards').getAttribute('type')==='checkbox','Offene Karten als gleichartige Checkbox');check(await page.locator('.fog-preview img').first().getAttribute('src').then(v=>v.startsWith('data:image/svg+xml')),'Nebelvorschau ersetzt volle Kartenvorschau');
 phase='online';const game=await serial(()=>newPlayGame(db,[a,b],{fog:true,cards:'open',diceHints:true,fieldHints:true},map));await db.query("update dungeon_game_player_states set state=state||'{\"reached\":[\"2\"],\"powerups\":[\"horn\",\"binocular\"],\"hornUses\":1}'::jsonb,revision=revision+1 where game_id=$1 and player_id=$2",[game,a.profile.id]);await page.goto(url+`/#/game?id=${game}`);await page.locator('#game-board-svg .game-cell-target').first().waitFor();check(await page.locator('#game-board-svg [data-cell-id="12"]').getAttribute('visibility')==='hidden','Boss hinter unbesiegtem Monster bleibt trotz Fernglas verdeckt');await page.locator('#use-horn').click();await page.waitForFunction(()=>document.querySelector('#game-board-svg [data-cell-id="12"]')?.getAttribute('visibility')==='visible');check(await page.locator('#game-board-svg [data-cell-id="12"]').getAttribute('visibility')==='visible','Horn zeigt entfernten Boss');await page.waitForFunction(()=>document.querySelector('#game-board-svg [data-cell-id="12"]')?.getAttribute('visibility')==='hidden',{},{timeout:14000});check(true,'Horn verschwindet selbstständig nach zehn Sekunden');
 await serial(()=>forceDice(db,[4,4,1,2]));await page.locator('#roll-dice').click();await page.waitForFunction(()=>!document.querySelector('.dice-presentation').hidden);check(await page.locator('.dice-presentation').evaluate(n=>n.style.getPropertyValue('--roll-duration'))==='6s','Lange Würfelanimation zeigt bestätigten Wurf');await page.locator('.roll-skip').click();await page.evaluate(()=>{window.__cleanBoard=document.querySelector('#game-board-svg');window.__cleanView=window.__cleanBoard.getAttribute('viewBox');});await refresh();check(await page.evaluate(()=>window.__cleanBoard===document.querySelector('#game-board-svg')&&window.__cleanView===window.__cleanBoard.getAttribute('viewBox')&&document.querySelector('.dice-presentation').hidden),'Aktualisieren bewahrt SVG/Zoom und wiederholt den Wurf nicht');
 await page.locator('#game-board-svg [data-cell-id="3"]').click({force:true});await page.waitForFunction(()=>document.querySelector('#game-board-svg .enemy-info[data-id="3"] [data-hit="1"]')?.getAttribute('fill')==='#375b48');check(true,'Normaler Monsterangriff funktioniert weiterhin');
 for(const [width,height] of [[1366,768],[740,360],[360,780]]){await page.setViewportSize({width,height});await page.waitForTimeout(100);const bounds=await page.locator('.game-board-stage').evaluate(n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom,width:r.width,height:r.height,viewport:innerHeight};});check(bounds.top>=0&&bounds.bottom<=bounds.viewport+1&&bounds.height>100,`Spielfeld passt bei ${width}×${height} in die feste Anzeige`);}
 await page.setViewportSize({width:1366,height:768});await serial(()=>db.query('select dungeon_private.finalize_game($1)',[game]));await refresh();await page.locator('.result-dialog[open]').waitFor();await page.locator('#watch-replay').click();await page.locator('#replay-board-svg').waitFor();check(await page.locator('#replay-player option').count()===2,'Ergebnis öffnet Wiederholung mit Spielerauswahl');await page.locator('#replay-play').click();await page.waitForTimeout(1100);check(Number(await page.locator('#replay-position').inputValue())>0,'Wiederholung zeigt fortschreitende bestätigte Stände');await page.locator('#replay-player').selectOption(b.profile.id);check(await page.locator('#replay-position').inputValue()==='0','Spielerwechsel beginnt eigenes Brett neu');
 await page.locator('.replay-dialog[open]').getByRole('button',{name:'Schließen',exact:true}).click();await page.locator('.result-dialog[open]').getByRole('button',{name:'Schließen',exact:true}).click();
 phase='death-order';const dead=await serial(()=>newPlayGame(db,[a],{},map));await db.query("update dungeon_game_player_states set state=state||'{\"lostLives\":10}'::jsonb,revision=revision+1 where game_id=$1",[dead]);await page.goto(url+`/#/game?id=${dead}`);await page.locator('#game-board-svg').waitFor();await serial(()=>forceDice(db,[1,1,1,1]));await page.locator('#roll-dice').click();await page.waitForFunction(()=>!document.querySelector('.dice-presentation').hidden);check(await page.locator('.life-loss-dialog').count()===0&&await page.locator('.result-dialog[open]').count()===0,'Bei automatischem Ausscheiden wird zuerst der Wurf gezeigt');await page.locator('.life-loss-dialog[open]').waitFor();check(await page.locator('.life-loss-dialog h2').textContent()==='Ausgeschieden'&&await page.locator('.result-dialog[open]').count()===0,'Ausscheiden wartet auf Animation und Bestätigung vor Schlusswertung');await page.locator('.life-loss-dialog').getByRole('button',{name:'Verstanden'}).click();await page.locator('.result-dialog[open]').waitFor();check(true,'Bestätigter Lebensverlust öffnet anschließend das Ergebnis');
 check(errors.length===0,`Keine JavaScript-Fehler: ${errors.join('; ')}`);console.log(`TOTAL ${checks} Online-Browserprüfungen bestanden.`);}
}catch(error){console.error('TESTPHASE',phase);if(page)console.error(await page.locator('.feedback,#map-save-status').allTextContents().catch(()=>[]));throw error;}finally{clearTimeout(watchdog);await browser?.close();await db?.close();server.kill();}
