import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {createShopDatabase} from './helpers/shop.mjs';import {modernFixture} from './helpers/game-upgrade.mjs';import {register,userRpc,publishFixture} from './helpers/games.mjs';import {newPlayGame,seedState,installTestDice,forceDice} from './helpers/turns.mjs';import {callRpc} from './helpers/database.mjs';
const migration=()=>readFile(new URL('../supabase/migrations/020_round_two.sql',import.meta.url),'utf8');
test('Runde 2: Migration, Horn, Sicht, Replay und Bestandsschutz',{timeout:120000},async t=>{
 const db=await createShopDatabase();try{
 const a=await register(db,'Rundezweiflo'),b=await register(db,'Rundezweijoni'),rpc=(u,n,p={})=>userRpc(db,u,n,p),original=await rpc(a,'get_player_profile');
 const oldMap=await publishFixture(db,a,'Alte Mine',modernFixture()),old=await newPlayGame(db,[a],{},oldMap);await db.query('select dungeon_private.finalize_game($1)',[old]);const oldResult=await rpc(a,'get_game_result',{p_game_id:old});const running=await newPlayGame(db,[a,b],{},oldMap);
 await db.exec(await migration());
 await t.test('Installiert auf 0.9.0 und wiederholt ohne Preis- oder Profiländerung',async()=>{const shop=await rpc(a,'get_marking_shop');assert.deepEqual(shop.items.map(i=>i.price),[0,10,20,30,40,50,60,70,80,90]);await db.exec(await migration());assert.deepEqual((await rpc(a,'get_marking_shop')).items,shop.items);assert.deepEqual((await rpc(a,'get_player_profile')).profile.preferences,original.profile.preferences);assert.deepEqual((await rpc(a,'get_game_result',{p_game_id:old})).game.results,oldResult.game.results);assert.equal((await callRpc(db,'app_status')).roundTwoVersion,1);});
 await t.test('Alte abgeschlossene Partie bekommt keine erfundene Wiederholung',async()=>{assert.equal((await rpc(a,'get_game_replay',{p_game_id:old})).available,false);});
 await t.test('Schon laufende Spiele erhalten ehrlich gekennzeichneten Teilverlauf',async()=>{await db.query('select dungeon_private.finalize_game($1)',[running]);const r=await rpc(a,'get_game_replay',{p_game_id:running});assert.equal(r.available,true);assert.ok(r.players.every(p=>!p.complete&&p.frames.length>=1));});
 await t.test('Installationsprüfung meldet sechsmal OK',async()=>{const checks=(await db.exec(await readFile(new URL('../supabase/migrations/021_check_round_two.sql',import.meta.url),'utf8')))[0].rows;assert.equal(checks.length,6);assert.ok(checks.every(r=>r.ergebnis==='OK'));});
 const d=modernFixture();d.allowedPowerups.push('horn');const map=await publishFixture(db,a,'Horn Mine',d),game=await newPlayGame(db,[a,b],{fog:true,cards:'open'},map);
 await t.test('Karten können das Horn freigeben; freie Gestaltung ohne zwei-Kisten-Warnung',async()=>{const report=(await db.query('select dungeon_private.map_report($1) r',[JSON.stringify(map.document||d)])).rows[0].r;assert.ok(!report.warnings.some(w=>w.message.includes('Originallevel')||w.message.includes('Name oder Bild')||w.message.includes('Kein Hintergrund')));});
 await t.test('Unbesiegtes Monster blockiert Sicht, besiegtes nicht; Fernglas hebt Blockade nicht auf',async()=>{const cells=async state=>(await db.query('select dungeon_private.game_visible_cells(g,$2) v from dungeon_games g where id=$1',[game,JSON.stringify(state)])).rows[0].v;const s={reached:['2'],powerups:[]};assert.ok((await cells(s)).includes('3'));assert.ok(!(await cells(s)).includes('12'));assert.ok(!(await cells({...s,powerups:['binocular']})).includes('12'));assert.ok((await cells({reached:['2','3']})).includes('12'));});
 await t.test('Truhe liefert einmaliges Horn, Nutzung ist idempotent und verbraucht keinen Zug',async()=>{
 await db.query("update dungeon_game_player_states set state=state||'{\"pendingChests\":[\"13\"]}'::jsonb,revision=revision+1 where game_id=$1 and player_id=$2",[game,a.profile.id]);let g=(await rpc(a,'get_game',{p_game_id:game})).game;
 assert.equal((await rpc(a,'choose_game_powerup',{p_game_id:game,p_chest_cell_id:'13',p_state_revision:g.turn.ownRevision,p_powerup:'horn',p_request_id:randomUUID()})).ok,true);g=(await rpc(a,'get_game',{p_game_id:game})).game;assert.equal(g.ownState.hornUses,1);
 const args={p_game_id:game,p_state_revision:g.turn.ownRevision,p_request_id:randomUUID()},one=await rpc(a,'use_game_horn',args),two=await rpc(a,'use_game_horn',args);assert.deepEqual(two,one);assert.equal(one.ok,true);const after=(await rpc(a,'get_game',{p_game_id:game})).game;assert.equal(after.phase,'waiting_roll');assert.equal(after.round,g.round);assert.equal(after.ownState.hornUses,0);assert.ok(Date.parse(after.ownState.hornUntil)-Date.parse(after.serverNow)>8000);assert.equal((await rpc(b,'use_game_horn',{p_game_id:game,p_state_revision:0,p_request_id:randomUUID()})).ok,false);
 });
 await t.test('Replay ist vor Ende gesperrt und enthält bestätigte Zustände samt Anfang',async()=>{assert.equal((await rpc(a,'get_game_replay',{p_game_id:game})).error,'GAME_CLOSED');await db.query('select dungeon_private.finalize_game($1)',[game]);const replay=await rpc(a,'get_game_replay',{p_game_id:game});assert.equal(replay.available,true);assert.equal(replay.definition.document.format,'dungeon-layout-v7');const own=replay.players.find(p=>p.id===a.profile.id);assert.equal(own.complete,true);assert.ok(own.frames.length>=3);assert.ok(own.frames.at(-1).state.powerups.includes('horn'));assert.ok(own.frames.some(f=>f.state.hornUses===1));});
 await t.test('Neue kosmetische Einstellungen validiert, Revisionen und Besitzprüfung bleiben',async()=>{let p=(await rpc(a,'get_player_profile')).profile;const prefs={...p.preferences,diceStyle:'midnight',cupStyle:'runic',campStyle:'moon',diceAnimation:'long'};const saved=await rpc(a,'update_player_preferences',{p_preferences:prefs,p_expected_revision:p.revision});assert.equal(saved.ok,true);assert.deepEqual(saved.profile.preferences,prefs);p=saved.profile;assert.equal((await rpc(a,'update_player_preferences',{p_preferences:{...prefs,diceStyle:'nope'},p_expected_revision:p.revision})).error,'PREFERENCES_INVALID');assert.equal((await rpc(a,'update_player_preferences',{p_preferences:{...prefs,markStyle:'seal'},p_expected_revision:p.revision})).error,'SHOP_STYLE_LOCKED');});
 await t.test('Replaytabellen sind privat; RPC erfordert Sitzung',async()=>{assert.equal((await db.query("select has_table_privilege('anon','dungeon_private.replay_frames','select') allowed")).rows[0].allowed,false);await assert.rejects(()=>callRpc(db,'get_game_replay',{p_session_token:'a'.repeat(64),p_game_id:game}),/SESSION_INVALID/);});
 }finally{await db.close();}
});
