import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {createUpgradedDatabase,modernFixture} from './helpers/game-upgrade.mjs';import {shopMigration} from './helpers/shop.mjs';
import {register,userRpc,publishFixture} from './helpers/games.mjs';import {newPlayGame,seedState,installTestDice,forceDice} from './helpers/turns.mjs';import {callRpc} from './helpers/database.mjs';

test('Markierungs-Shop und Diamantengutschriften',{timeout:120000},async t=>{
 const db=await createUpgradedDatabase();const a=await register(db,'Altflo'),b=await register(db,'Altjoni');
 const rpc=(u,name,args={})=>userRpc(db,u,name,args),profile=async u=>(await rpc(u,'get_player_profile')).profile,shop=async u=>rpc(u,'get_marking_shop'),buy=(u,style,id=randomUUID())=>rpc(u,'buy_marking',{p_style:style,p_request_id:id});
 const map=await publishFixture(db,a,'Shop-Mine',modernFixture()),old=await newPlayGame(db,[a,b],{},map);
 await seedState(db,old,a,{diamonds:40,goldPoints:5,monsterHits:{12:10}});await seedState(db,old,b,{diamonds:-2});await db.query('select dungeon_private.finalize_game($1)',[old]);
 const before=(await rpc(a,'get_game',{p_game_id:old})).game,original=await profile(a);
 try{
  await t.test('Bestehende Ergebnisse, Einstellungen und Sitzung bleiben erhalten; Diamanten werden rückwirkend gutgeschrieben',async()=>{
   await db.exec(await shopMigration());const p=await profile(a);assert.deepEqual(p.stats,original.stats);assert.deepEqual(p.preferences,original.preferences);assert.equal(p.revision,original.revision);assert.equal(p.cosmetics.balance,before.results.find(r=>r.playerId===a.profile.id).diamonds);assert.deepEqual(p.cosmetics.unlocked,['cross','pencil']);assert.deepEqual((await rpc(a,'get_game',{p_game_id:old})).game.ownState,before.ownState);
  });
  await t.test('Negative Spiel-Diamanten bleiben negative Punkte, belasten aber kein Shop-Guthaben',async()=>{const p=await profile(b);assert.equal(p.cosmetics.balance,0);assert.equal(before.results.find(r=>r.playerId===b.profile.id).points,-6);assert.equal((await db.query('select amount from dungeon_private.marking_credits where player_id=$1',[b.profile.id])).rows[0].amount,0);});
  const fresh=await register(db,'Neuflo');
  await t.test('Neue Spieler beginnen mit X, sieben Stile und ohne Guthaben',async()=>{const s=await shop(fresh);assert.equal(s.profile.preferences.markStyle,'cross');assert.deepEqual(s.profile.cosmetics.unlocked,['cross']);assert.equal(s.profile.cosmetics.balance,0);assert.equal(s.items.length,7);assert.equal(s.items.filter(i=>i.owned).length,1);assert.deepEqual(s.items.map(i=>i.price),[0,5,10,15,20,25,30]);});
  await t.test('Gesperrte Markierung wird auch bei direktem RPC-Aufruf abgewiesen',async()=>{const p=await profile(fresh);const r=await rpc(fresh,'update_player_preferences',{p_preferences:{...p.preferences,markStyle:'stars'},p_expected_revision:p.revision});assert.equal(r.error,'SHOP_STYLE_LOCKED');assert.equal((await profile(fresh)).revision,p.revision);});
  await t.test('Zu wenig Guthaben, falscher Stil und fehlende UUID buchen nichts ab',async()=>{assert.equal((await buy(fresh,'waves')).error,'SHOP_INSUFFICIENT_DIAMONDS');assert.equal((await buy(fresh,'unknown')).error,'SHOP_STYLE_INVALID');assert.equal((await buy(fresh,'waves',null)).error,'SHOP_REQUEST_INVALID');assert.equal((await profile(fresh)).cosmetics.spent,0);});
  await t.test('Regulärer letzter Angriff löst einmalige Gutschrift inklusive Schlusswertung aus',async()=>{
   const id=await newPlayGame(db,[fresh],{},map);await seedState(db,id,fresh,{diamonds:12,goldPoints:5,lostLives:3,reached:['3'],monsterHits:{3:2,12:11}});await installTestDice(db);await forceDice(db,[4,4,1,1]);let g=(await rpc(fresh,'get_game',{p_game_id:id})).game;await rpc(fresh,'roll_game_dice',{p_game_id:id,p_round:g.round,p_request_id:randomUUID()});g=(await rpc(fresh,'get_game',{p_game_id:id})).game;
   assert.equal((await rpc(fresh,'play_game_action',{p_game_id:id,p_round:g.round,p_state_revision:g.turn.ownRevision,p_action:'cell',p_cell_id:'12',p_use_red:false,p_middle_cell_id:null,p_use_axe:false,p_request_id:randomUUID()})).ok,true);
   g=(await rpc(fresh,'get_game',{p_game_id:id})).game;assert.equal(g.status,'finished');assert.equal((await profile(fresh)).cosmetics.balance,g.results[0].diamonds);assert.equal(g.results[0].points,g.results[0].diamonds*3+4);await db.query('select dungeon_private.credit_game_diamonds($1)',[id]);await db.query('select dungeon_private.finalize_game($1)',[id]);assert.equal((await profile(fresh)).cosmetics.balance,g.results[0].diamonds);
  });
  await t.test('Kauf und identischer Retry belasten nur einmal; UUID kann nicht für anderen Stil wiederverwendet werden',async()=>{const id=randomUUID(),start=await profile(a),one=await buy(a,'stars',id),two=await buy(a,'stars',id);assert.equal(one.ok,true);assert.equal(two.replayed,true);assert.equal(two.profile.cosmetics.balance,start.cosmetics.balance-20);assert.equal(two.profile.cosmetics.spent,20);assert.equal((await buy(a,'runes',id)).error,'SHOP_REQUEST_INVALID');assert.deepEqual((await profile(a)).stats,start.stats);assert.deepEqual((await rpc(a,'get_game',{p_game_id:old})).game.ownState,before.ownState);});
  await t.test('Erneuter Kauf eines vorhandenen Stils und kostenloses X buchen nichts ab',async()=>{const start=await profile(a);assert.equal((await buy(a,'stars')).charged,0);assert.equal((await buy(a,'cross')).charged,0);assert.equal((await profile(a)).cosmetics.balance,start.cosmetics.balance);});
  await t.test('Zwei Kaufanfragen können das vorhandene Guthaben nicht überziehen',async()=>{const calls=await Promise.all([db.query('select public.buy_marking($1,$2,$3) result',[a.session.token,'waves',randomUUID()]),db.query('select public.buy_marking($1,$2,$3) result',[a.session.token,'solid',randomUUID()])]);const result=calls.map(c=>c.rows[0].result);assert.equal(result.filter(c=>c.ok).length,1);assert.equal(result.find(c=>!c.ok).error,'SHOP_INSUFFICIENT_DIAMONDS');assert.ok((await profile(a)).cosmetics.balance>=0);});
  await t.test('Gekaufter Stil kann gewählt werden; veraltete Profile überschreiben keine Einstellungen',async()=>{const p=await profile(a),prefs={...p.preferences,markStyle:'stars',reduceMotion:true};const saved=await rpc(a,'update_player_preferences',{p_preferences:prefs,p_expected_revision:p.revision});assert.equal(saved.ok,true);assert.deepEqual(saved.profile.preferences,prefs);assert.equal((await rpc(a,'update_player_preferences',{p_preferences:original.preferences,p_expected_revision:p.revision})).error,'PROFILE_CHANGED');});
  await t.test('Laufende und abgebrochene Spiele erzeugen keine Gutschrift',async()=>{const id=await newPlayGame(db,[fresh],{},map);await seedState(db,id,fresh,{diamonds:100});const start=await profile(fresh);await db.query('select dungeon_private.credit_game_diamonds($1)',[id]);await db.query("update public.dungeon_games set status='cancelled' where id=$1",[id]);await db.query('select dungeon_private.credit_game_diamonds($1)',[id]);assert.equal((await profile(fresh)).cosmetics.balance,start.cosmetics.balance);assert.equal((await db.query('select count(*)::int n from dungeon_private.marking_credits where game_id=$1',[id])).rows[0].n,0);});
  await t.test('Wiederholte Migration verändert Guthaben, Käufe und aktive Markierung nicht',async()=>{const start=await profile(a);await db.exec(await shopMigration());const now=await profile(a);assert.deepEqual(now,start);assert.ok(!now.cosmetics.unlocked.includes('runes'));});
  await t.test('Shopdaten sind privat und alle Shop-Aufrufe erfordern eine gültige Sitzung',async()=>{await assert.rejects(()=>callRpc(db,'get_marking_shop',{p_session_token:'a'.repeat(64)}),/SESSION_INVALID/);await assert.rejects(()=>callRpc(db,'buy_marking',{p_session_token:'a'.repeat(64),p_style:'stars',p_request_id:randomUUID()}),/SESSION_INVALID/);for(const table of ['marking_catalog','marking_credits','marking_purchases','marking_requests'])assert.equal((await db.query(`select has_table_privilege('anon','dungeon_private.${table}','select') allowed`)).rows[0].allowed,false);assert.equal((await db.query("select has_function_privilege('anon','dungeon_private.credit_game_diamonds(uuid)','execute') allowed")).rows[0].allowed,false);});
  await t.test('Installationsprüfung meldet siebenmal OK',async()=>{const rows=(await db.exec(await readFile(new URL('../supabase/migrations/019_check_marking_shop.sql',import.meta.url),'utf8')))[0].rows;assert.equal(rows.length,7);assert.ok(rows.every(r=>r.ergebnis==='OK'));assert.equal((await callRpc(db,'app_status')).shopSchemaVersion,1);});
 }finally{await db.close();}
});
