// Echte Desktop-/Handybrowser und isoliertes PostgreSQL. Keine Live-Schreibzugriffe.
import {chromium} from 'playwright';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {createRequire} from 'node:module';import {mkdir} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import {randomUUID} from 'node:crypto';
import {createUpgradedDatabase,modernFixture} from './helpers/game-upgrade.mjs';import {register,userRpc,publishFixture} from './helpers/games.mjs';import {callRpc} from './helpers/database.mjs';import {installTestDice,forceDice,newPlayGame,seedState} from './helpers/turns.mjs';import {goalDefault} from '../web/js/maps/features.js';import {CONFIG} from '../web/js/config.js';

const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../',import.meta.url)),address='http://localhost:5197';
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,PORT:'5197'},stdio:'ignore'}),db=await createUpgradedDatabase(),sockets=new Set(),errors=[],requests=[],images=new Map();
let queue=Promise.resolve(),lastSignal=0,browser,page,phone,checks=0,assetReads=0,dropTurn=false;
const serial=fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;};
const check=(value,label)=>{assert.ok(value,label);checks++;console.log(`PASS ${label}`);};
async function signals(){for(const s of (await db.query('select * from realtime.test_signals where id>$1 order by id',[lastSignal])).rows){lastSignal=s.id;for(const socket of sockets)if(socket.topics.has(`realtime:${s.topic}`))socket.ws.send(JSON.stringify({topic:`realtime:${s.topic}`,event:'broadcast',payload:{type:'broadcast',event:'changed',payload:s.payload},ref:null}));}}
async function rpc(user,name,args={}){return serial(async()=>{const data=await userRpc(db,user,name,args);await signals();return data;});}
async function gateway(context){
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await context.routeWebSocket(url=>url.href.startsWith(CONFIG.supabaseUrl.replace('https:','wss:')+'/realtime/'),ws=>{
  const socket={ws,topics:new Set()};sockets.add(socket);ws.onClose(()=>sockets.delete(socket));ws.onMessage(text=>{const m=JSON.parse(text.toString());if(m.event==='phx_join'){socket.topics.add(m.topic);ws.send(JSON.stringify({topic:m.topic,event:'phx_reply',ref:m.ref,join_ref:m.join_ref,payload:{status:'ok',response:{}}}));}else if(m.event==='heartbeat')ws.send(JSON.stringify({topic:'phoenix',event:'phx_reply',ref:m.ref,payload:{status:'ok',response:{}}}));});
 });
 await context.route(`${CONFIG.supabaseUrl}/**`,async route=>{
  const req=route.request(),url=new URL(req.url()),headers={'access-control-allow-origin':'*','access-control-allow-methods':'POST,GET,OPTIONS','access-control-allow-headers':'apikey,content-type,x-session-token'};
  if(req.method()==='OPTIONS'){await route.fulfill({status:204,headers});return;}
  if(url.pathname.startsWith('/storage/v1/object/public/map-assets/')){assetReads++;const img=images.get(url.pathname.split('/map-assets/')[1]);await route.fulfill({status:img?200:404,headers:{...headers,'content-type':'image/png'},body:img||''});return;}
  const method=url.pathname.split('/').at(-1),args=req.postDataJSON();requests.push({method,args});
  try{const data=await serial(async()=>{const answer=await callRpc(db,method,args);await signals();return answer;});if(dropTurn&&method==='play_game_action'&&data.ok){dropTurn=false;await route.abort('failed');return;}await route.fulfill({status:200,headers,body:JSON.stringify(data)});}catch(e){await route.fulfill({status:400,headers,body:JSON.stringify({message:e.message})});}
 });
}
async function login(p,name){await p.goto(address);await p.locator('#auth-form').waitFor();await p.fill('#username',name);await p.fill('#password','testing42');await p.click('#auth-submit');await p.locator('.home-view').waitFor();}
async function open(p,id,lobby=false){await p.goto(address+`/#/game?id=${id}`);await p.locator(lobby?'#start-game':'#game-board-svg').waitFor({timeout:25000});}
const cell=(p,id)=>p.locator(`#gameTargets [data-cell-id="${id}"]`);
async function play(p,id){await p.waitForFunction(id=>document.querySelector(`#gameTargets [data-cell-id="${id}"]`)?.getAttribute('aria-disabled')==='false',String(id));await cell(p,id).focus();await cell(p,id).press('Enter');}
async function refresh(p){await Promise.all([p.waitForResponse(r=>r.url().endsWith('/rpc/get_game')&&r.status()===200),p.evaluate(()=>document.querySelector('#refresh-game').click())]);await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
const get=async(u,id)=>(await rpc(u,'get_game',{p_game_id:id})).game;
async function acknowledge(p){const d=p.locator('.life-loss-dialog');if(await d.count())await d.getByRole('button',{name:'Verstanden'}).click();}
// Prüft Layout, Vollbild, Live-Animation und Eingaben über echte Browser.
async function inViewport(p,selectors){
 return p.evaluate(selectors=>selectors.map(selector=>{const n=document.querySelector(selector),r=n?.getBoundingClientRect();return {selector,visible:r&&r.width>0&&r.height>0&&r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1,rect:r?{x:r.x,y:r.y,w:r.width,h:r.height}:null};}),selectors);
}
async function stableNodes(p){return p.evaluate(()=>{const b=document.querySelector('#game-board-svg');window.__tableStable={board:b,box:b.getAttribute('viewBox'),images:[...b.querySelectorAll('image')],face:document.querySelector('#game-dice .dice-face'),mini:document.querySelector('.opponent-miniature svg'),score:document.querySelector('#own-points'),target:b.querySelector('[data-cell-id="3"]')};});}
async function noAnimation(p){return p.locator('.dice-presentation').evaluate(n=>n.hidden);}
async function stopAnimation(p){await p.locator('.dice-presentation .roll-skip').evaluate(n=>{if(!n.closest('.dice-presentation').hidden)n.click();});}
try{
 await installTestDice(db);const flo=await register(db,'Flo'),joni=await register(db,'Joni'),mira=await register(db,'Mira');await mkdir(root+'/test-results',{recursive:true});
 for(let i=0;i<100;i++){try{if((await fetch(address)).ok)break;}catch{}await new Promise(r=>setTimeout(r,30));}
 let args=[];if(process.env.WUERFELDUNGEON_CHROMIUM_MODULE)args=require(process.env.WUERFELDUNGEON_CHROMIUM_MODULE).default.args.filter(v=>!['--single-process','--disable-web-security'].includes(v));
 browser=await chromium.launch({headless:true,executablePath:process.env.WUERFELDUNGEON_CHROMIUM_PATH||undefined,args});
 const desktop=await browser.newContext({viewport:{width:1440,height:900}}),mobile=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});await gateway(desktop);await gateway(mobile);page=await desktop.newPage();phone=await mobile.newPage();
 async function image(name){const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=96;c.height=96;const x=c.getContext('2d');x.fillStyle='#78926f';x.beginPath();x.arc(48,48,36,0,Math.PI*2);x.fill();return c.toDataURL('image/png').split(',')[1];}),'base64');const path=`${randomUUID()}/${randomUUID()}.png`;images.set(path,png);await db.query("insert into dungeon_private.assets(path,kind,owner_id,mime_type,bytes) values($1,'map',$2,'image/png',$3)",[path,flo.profile.id,png.length]);return {src:`asset:${path}`,width:96,height:96,name};}
 const d=modernFixture();d.rooms.find(r=>r.id===3).image=await image('Troll');d.rooms.find(r=>r.id===3).imageLayout={x:0,y:0,w:8,h:8};d.rules.goals=[{...goalDefault(),type:'allType',fieldType:'trap',reward:{first:4,later:2}},{...goalDefault(),type:'connect',cellIds:[1,11],reward:{first:5,later:0}}];
 const map=await publishFixture(db,flo,'Glutmine',d),id=await serial(()=>newPlayGame(db,[flo,joni],{cards:'open',diceHints:true,fieldHints:true},map));await login(page,'flo');await login(phone,'joni');
 check(await page.locator('.welcome-line,.camp-strip,.phase-explanation').count()===0&&await page.locator('.menu-card').count()===5,'Lager zeigt die fünf Funktionen ohne doppelte Begrüßung oder Zähler');
 check(await page.locator('.nav-profile>span:not(.avatar)').innerText()==='Flo'&&await page.locator('#version-label').innerText()===CONFIG.version,'Profil und aktuelle Version bleiben im Lager sichtbar');await page.screenshot({path:root+'/test-results/table-lager.png',fullPage:true});
 await page.click('.menu-card[href="#/profile"]');await page.locator('#profile-form').waitFor();check(await page.locator('.nav-back').getAttribute('href')==='#/home'&&!(await page.locator('body').innerText()).includes('Test-Ergebnisse'),'Profil hat einen Zurück-Pfeil und keine Klassische Regeln-Erklärung');await page.locator('.nav-back').click();await page.locator('.home-view').waitFor();
 await open(page,id);await open(phone,id);await page.locator('.opponent-miniature').waitFor();await phone.locator('.opponent-miniature').waitFor();
 check(await page.locator('.game-immersive').count()===1&&await page.locator('.opponent-seat').count()===1&&await page.locator('.opponent-name').innerText()==='Joni','Spielraum öffnet fest über das ganze Fenster; nur Gegner stehen oben');
 let bounds=await inViewport(page,['.play-toolbar','.room-players','#game-board-stage','.game-side','.game-dock','#roll-dice']);check(bounds.every(b=>b.visible),`Desktop: alle Anzeigen und Würfelknopf liegen im Fenster (${JSON.stringify(bounds)})`);
 check(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1&&document.documentElement.scrollWidth<=innerWidth),'Desktop-Spielansicht benötigt kein Seitenscrollen');
 let phoneBounds=await inViewport(phone,['.play-toolbar','.room-players','#game-board-stage','.game-side','.game-dock','.life-boxes']);check(phoneBounds.every(b=>b.visible),`Handy quer: alle Anzeigen liegen im Fenster (${JSON.stringify(phoneBounds)})`);
 check(await phone.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1&&document.documentElement.scrollWidth<=innerWidth),'Handy im Querformat bleibt ohne Seitenscrollen spielbar');
 check(await phone.locator('.game-tasks').evaluate(n=>{const b=n.getBoundingClientRect();return [...n.querySelectorAll('.task-cell')].every(c=>{const r=c.getBoundingClientRect();return r.top>=b.top&&r.bottom<=b.bottom+1;});}),'Beide kurzen Bonusaufgaben sind im Handy-Querformat vollständig sichtbar');
 await page.screenshot({path:root+'/test-results/table-desktop-start.png'});await phone.screenshot({path:root+'/test-results/table-landscape-start.png'});
 const geometry=await page.locator('#roomsLayer .room-body').evaluateAll(nodes=>nodes.map(n=>['x','y','width','height'].map(a=>n.getAttribute(a))));
 check(await noAnimation(page)&&await noAnimation(phone),'Beim Öffnen wird kein alter Wurf abgespielt');
 await serial(()=>forceDice(db,[2,4,1,1]));dropTurn=false;await page.click('#roll-dice');await page.locator('.dice-presentation:not([hidden])').waitFor();await phone.locator('.dice-presentation:not([hidden])').waitFor();
 check(await page.locator('.dice-presentation .dice-cup').count()===1&&await phone.locator('.dice-presentation .roll-reveal .dice-face').count()===4,'Beide Spieler sehen Becher und dieselben vier Ergebniswürfel');check(await page.locator('#game-dice .dice-face').count()===4&&await phone.locator('#game-dice .dice-face').count()===4,'Die vier Würfel sind anschließend in der festen unteren Leiste');
 await page.screenshot({path:root+'/test-results/table-roll.png'});await stopAnimation(page);await stopAnimation(phone);await stableNodes(page);const downloads=assetReads;await refresh(page);await refresh(phone);
 check(await noAnimation(page)&&await noAnimation(phone),'Refresh startet die übersprungene Animation nicht erneut');
 await page.getByRole('button',{name:'Vergrößern',exact:true}).click();await cell(page,3).focus();await stableNodes(page);await refresh(page);
 check(await page.evaluate(()=>{const s=window.__tableStable,b=document.querySelector('#game-board-svg');return b===s.board&&b.getAttribute('viewBox')===s.box&&s.images.every(n=>n.isConnected)&&s.mini===document.querySelector('.opponent-miniature svg')&&s.face===document.querySelector('#game-dice .dice-face')&&s.score===document.querySelector('#own-points')&&document.activeElement===s.target;}),'Live-Updates bewahren Plan, Zoom, Bilder, Gegnerkarte, Würfel und Tastaturfokus');check(assetReads===downloads,'Unveränderte Updates laden keine Kartenbilder erneut');
 // Native Vollbildwurzel und darin sichtbare Dialoge. Kein Spielbefehl dabei.
 const before=await get(flo,id),viewBefore=await page.locator('#game-board-svg').getAttribute('viewBox');await page.click('#game-fullscreen');await page.waitForFunction(()=>Boolean(document.fullscreenElement));
 check(await page.evaluate(()=>document.fullscreenElement===document.documentElement),'Vollbild umfasst auch Dialoge und Meldungen');await page.locator('[data-task="custom"]').click();await page.locator('.task-dialog').waitFor();check((await page.locator('.task-dialog').innerText()).includes('Durchgängiger Weg')&&await page.locator('.task-dialog [data-task-cell]').count()===2,'Bonusdetails sind im nativen Vollbild sichtbar');await page.locator('.task-dialog').getByRole('button',{name:'Schließen',exact:true}).click();
 await page.click('#game-fullscreen');await page.waitForFunction(()=>!document.fullscreenElement);check((await get(flo,id)).revision===before.revision&&await page.locator('#game-board-svg').getAttribute('viewBox')===viewBefore,'Vollbild ein/aus verändert weder Zoom noch Spielstand');
 // Derselbe Wurf wird nach echter Navigation/Reload nicht wieder animiert.
 await page.reload();await page.locator('#game-board-svg').waitFor();check(await noAnimation(page)&&await page.locator('#game-dice .dice-face').count()===4,'Wiederverbinden zeigt gespeicherten Wurf ohne erneute Animation');
 // Echter Fingertipp im Querformat.
 await play(page,1);const cdp=await mobile.newCDPSession(phone);await cell(phone,1).scrollIntoViewIfNeeded();const r=await cell(phone,1).boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width/2,y:r.y+r.height/2,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await phone.locator('#roll-dice').waitFor();
 check((await get(joni,id)).ownState.reached.includes('1')&&(await get(flo,id)).round===2,'Fingertipp spielt einen regulären Zug und wechselt den Roller');
 check(await page.locator('[data-marked-cell="1"] path').first().getAttribute('stroke-width')==='2.8'&&await page.locator('[data-marked-cell="1"] path').first().getAttribute('opacity')==='0.72','Erreichte Felder erhalten kräftige Bleistiftmarkierungen');
 check(JSON.stringify(geometry)===JSON.stringify(await page.locator('#roomsLayer .room-body').evaluateAll(nodes=>nodes.map(n=>['x','y','width','height'].map(a=>n.getAttribute(a))))),'Neue Oberfläche und Markierungen verändern keine Kartenposition oder Größe');
 // Reduce Motion respektieren, auch beim zweiten eigenen Serverwurf.
 await rpc(joni,'update_player_preferences',{p_preferences:{markStyle:'cross',sound:true,music:false,reduceMotion:true},p_expected_revision:joni.profile.revision});await phone.reload();await phone.locator('#game-board-svg').waitFor();await serial(()=>forceDice(db,[3,4,1,1]));await phone.click('#roll-dice');await phone.locator('.dice-presentation:not([hidden])').waitFor();check(await phone.locator('.dice-presentation.still-roll').count()===1&&await phone.locator('.dice-cup').evaluate(n=>getComputedStyle(n).display)==='none','Weniger Bewegung zeigt Ergebnisse ohne Becherbewegung');await stopAnimation(phone);await stopAnimation(page);
 await phone.screenshot({path:root+'/test-results/table-landscape.png'});await page.screenshot({path:root+'/test-results/table-desktop.png'});
 // Pause oben erreichbar; keine zusätzlichen Hinweise im normalen Zug.
 await page.click('#pause-game');await phone.waitForFunction(()=>document.querySelector('#game-status')?.textContent==='Pausiert');check(await phone.locator('.center-state.paused-state').count()===1&&await phone.locator('#pause-game').count()===0,'Pause ist für alle sichtbar und nur vom Host steuerbar');await page.click('#pause-game');await phone.waitForFunction(()=>document.querySelector('#game-status')?.textContent==='Laufend');
 check(!(await page.locator('body').innerText()).includes('Du darfst alle vier')&&!(await page.locator('body').innerText()).includes('Wähle ein passendes Feld'),'Gewöhnliche Züge verzichten auf wiederkehrende Erklärtexte');
 // Große Meldung für einen Gegnerabschluss, mit Livebild/Original-Schutz.
 const combat=await serial(()=>newPlayGame(db,[flo,joni],{cards:'open'},map));for(const u of [flo,joni])await serial(()=>seedState(db,combat,u,{reached:['2'],monsterHits:{3:1}}));await open(page,combat);await open(phone,combat);await serial(()=>forceDice(db,[4,4,1,2]));await page.click('#roll-dice');await play(phone,3);await page.locator('.toast-prominent').waitFor();check((await page.locator('.toast-prominent').innerText()).includes('Joni hat Troll besiegt'),'Gegnersieg erscheint als große Meldung in der Mitte');let toastBounds=await inViewport(page,['.toast-prominent']);check(toastBounds.every(b=>b.visible),'Große Meldung bleibt innerhalb des sichtbaren Fensters');await play(page,3);
 // Hochformat bleibt bedienbar, Hinweisknopf lässt sich ausblenden.
 await phone.setViewportSize({width:390,height:844});await phone.locator('.rotate-hint').waitFor();phoneBounds=await inViewport(phone,['.play-toolbar','#game-board-stage','.game-side','.game-dock']);check(phoneBounds.every(b=>b.visible)&&await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight+1),'Handy hoch: Plan, Leben und Ressourcen bleiben im festen Fenster');await phone.getByRole('button',{name:'Querformat-Hinweis schließen'}).click();check(await phone.locator('.rotate-hint').evaluate(n=>n.hidden),'Querformat-Hinweis ist optional und schließbar');await phone.screenshot({path:root+'/test-results/table-portrait.png'});
 // Fehlende native Fullscreen API ist ein überprüfter, verlustfreier Rückfall.
 await page.evaluate(()=>{for(const key of ['requestFullscreen','webkitRequestFullscreen'])Object.defineProperty(document.documentElement,key,{value:undefined,configurable:true});});const fallbackBefore=await get(flo,combat);await page.click('#game-fullscreen');await page.waitForFunction(()=>document.querySelector('#toast-region')?.textContent.includes('füllt bereits das Fenster'));check((await get(flo,combat)).revision===fallbackBefore.revision&&await page.locator('.game-immersive').count()===1,'Ohne Vollbild-API bleibt die Fensteransicht vollständig nutzbar');await page.evaluate(()=>{delete document.documentElement.requestFullscreen;delete document.documentElement.webkitRequestFullscreen;});
 // Spielmenü statt großer Verwaltungsfelder; Back restauriert die App.
 await page.click('#game-menu-button');await page.locator('#game-menu:not([hidden])').waitFor();check(await page.locator('#cancel-game').isVisible()&&await page.locator('.host-transfer select').isVisible(),'Abbruch und Hostwechsel bleiben im kompakten Spielmenü verfügbar');await page.keyboard.press('Escape');check(await page.locator('#game-menu').evaluate(n=>n.hidden),'Escape schließt das Spielmenü');
 await page.locator('.table-back').click();await page.locator('.play-view').waitFor();check(await page.evaluate(()=>!document.body.classList.contains('game-open')&&getComputedStyle(document.querySelector('.site-header')).display!=='none')&&await page.locator('.nav-back').getAttribute('href')==='#/home','Zurück zeigt die Spielauswahl mit normaler Navigation');check(await page.locator('.dice-presentation').count()===0,'Animation und Spiel-Overlays werden beim Verlassen entfernt');
 // Kein legaler Zug bei beiden: Der Server beendet die Runde im Wurfbefehl.
 // Das bestätigte Ereignis muss dennoch sichtbar sein, ohne alte Kombinationen.
 const automatic=await serial(()=>newPlayGame(db,[flo,joni],{cards:'open',diceHints:true},map));await open(page,automatic);await open(phone,automatic);await serial(()=>forceDice(db,[1,1,1,1]));await page.click('#roll-dice');await page.locator('.life-loss-dialog').waitFor();await phone.locator('.life-loss-dialog').waitFor();
 const automaticState=await get(flo,automatic),automaticPeer=await get(joni,automatic);
 check(automaticState.round===2&&automaticState.phase==='waiting_roll'&&automaticState.dice===null&&automaticState.ownState.lostLives===1&&automaticPeer.ownState.lostLives===1,'Runde ohne legale Züge endet serverseitig automatisch mit je einem Lebensverlust');
 check(await page.locator('.dice-presentation').getAttribute('data-round')==='1'&&await phone.locator('.dice-presentation').getAttribute('data-round')==='1'&&await page.locator('.roll-reveal .dice-face').count()===4&&await phone.locator('.roll-reveal .dice-face').count()===4&&await page.locator('.roll-caption').innerText()==='Flo würfelt','Auch automatisch abgeschlossene Runden zeigen beiden Spielern den tatsächlichen Wurf und Roller');
 check(await page.locator('#game-dice .dice-face').count()===4&&await phone.locator('#game-dice .dice-face').count()===4&&await page.locator('.combination').count()===0&&await phone.locator('.combination').count()===0,'Letzter Wurf bleibt unten sichtbar, ohne Kombinationen für die nächste Runde anzubieten');
 await acknowledge(page);await acknowledge(phone);await stopAnimation(page);await stopAnimation(phone);await refresh(page);await refresh(phone);check(await noAnimation(page)&&await noAnimation(phone),'Aktualisieren wiederholt auch einen automatisch abgeschlossenen Wurf nicht');
 await page.reload();await page.locator('#game-board-svg').waitFor();check(await noAnimation(page)&&await page.locator('#game-dice').getAttribute('aria-label')==='Letzter Wurf · Runde 1','Wiederverbinden erhält den letzten abgeschlossenen Wurf ohne Wiederholung');
 await serial(()=>forceDice(db,[2,2,2,2]));await phone.click('#roll-dice');await page.locator('.life-loss-dialog').waitFor();await phone.locator('.life-loss-dialog').waitFor();check((await get(flo,automatic)).round===3&&await page.locator('.dice-presentation').getAttribute('data-round')==='2'&&await page.locator('.roll-caption').innerText()==='Joni würfelt'&&await page.locator('#game-dice .dice-face').first().getAttribute('title')==='Weiß · 2','Der nächste automatische Wurf ersetzt den vorherigen mit korrekter Runde und korrektem Roller');await acknowledge(page);await acknowledge(phone);await stopAnimation(page);await stopAnimation(phone);
 // Viele Gegner + viele Zielfelder + alle Powerups: auch kleine Breiten.
 const crowded=await serial(()=>newPlayGame(db,[flo,joni,mira],{cards:'open'},map));await serial(()=>seedState(db,crowded,flo,{extraLives:3,redUses:6,torchUses:2,axeUses:2,powerups:['extraLife','redDice','torch','axe'],reached:['1','2']}));await open(page,crowded);await page.locator('.opponent-seat').nth(1).waitFor();
 for(const size of [{width:1366,height:768},{width:1024,height:600},{width:740,height:360},{width:740,height:320},{width:360,height:780}]){await page.setViewportSize(size);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const b=await inViewport(page,['.play-toolbar','.room-play','.game-dock','.life-boxes','.score-resources']);check(b.every(r=>r.visible)&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight+1),`Alle Ressourcen und 14 Lebensfelder passen bei ${size.width}×${size.height} (${JSON.stringify(b)})`);}
 const friends=[];for(const name of ['Michi','Phil','Johanna','Petra'])friends.push(await serial(()=>register(db,name)));
 const many=await serial(()=>newPlayGame(db,[flo,joni,mira,...friends],{maxPlayers:16,cards:'open'},map));await open(page,many);await page.locator('.opponent-seat').nth(5).waitFor();
 const first=await page.locator('.opponent-seat').first().boundingBox(),rail=await page.locator('.room-players').boundingBox();check(first.x>=rail.x-1,'Viele Gegner beginnen am sichtbaren linken Rand');await page.locator('.opponent-seat').last().scrollIntoViewIfNeeded();const last=await page.locator('.opponent-seat').last().boundingBox();check(last.x+last.width<=rail.x+rail.width+1,'Auch der letzte Gegner bleibt über die kompakte Leiste erreichbar');
 check(errors.length===0,`Keine JavaScript-Fehler (${errors.join('; ')})`);console.log(`${checks} Spieloberflächen-Browserprüfungen erfolgreich.`);
}catch(e){console.error(e.stack);await page?.screenshot({path:root+'/test-results/table-error.png'}).catch(()=>{});throw e;}finally{await browser?.close();server.kill();await queue;await db.close();}
